// Generated from Pizza Hut Australia's official store and product APIs by scripts/import-pizza-hut.mjs.
// The feed publishes item energy. Pizza kJ values are explicitly based on the Original Pan base; macros are not included.
export type PizzaHutMenuDatum = readonly [name: string, category: string, sizeName: string, productType: string, kilojoules: number];

export const pizzaHutMenuSource = {"configurationUrl":"https://discover.prod.pizzahutaustralia.com.au/api/v1/Configuration","productApi":"https://product.prod.pizzahutaustralia.com.au","storeCode":1002,"storeName":"Yamanto"} as const;

export const pizzaHutMenu: readonly PizzaHutMenuDatum[] = [
  ["5 Cheesy Spud Bites — Standard","Sides","Standard","Sides",1261],
  ["8 Cheesy Spud Bites — Standard","Sides","Standard","Sides",1261],
  ["Aioli — 12 Wings","Wings","12 Wings","WingsStreet",5575],
  ["Aioli — 6 Wings","Wings","6 Wings","WingsStreet",2787],
  ["BBQ Beef — Large Original Pan","Pizza","Large","Pizzas",7607],
  ["BBQ Beef — Medium Original Pan","Pizza","Medium","Pizzas",4900],
  ["BBQ Cheeseburger — Large Original Pan","Pizza","Large","Pizzas",8421],
  ["BBQ Cheeseburger — Medium Original Pan","Pizza","Medium","Pizzas",5366],
  ["BBQ Chicken — Large Original Pan","Pizza","Large","Pizzas",7587],
  ["BBQ Chicken — Medium Original Pan","Pizza","Medium","Pizzas",4908],
  ["BBQ Meatlovers — Large Original Pan","Pizza","Large","Pizzas",8411],
  ["BBQ Meatlovers — Medium Original Pan","Pizza","Medium","Pizzas",5530],
  ["BBQ Meatlovers Loaded Garlic Bread — Standard","Sides","Standard","Sides",2361],
  ["Buffalo — 12 Wings","Wings","12 Wings","WingsStreet",5356],
  ["Buffalo — 6 Wings","Wings","6 Wings","WingsStreet",2678],
  ["Buffalo Chicken Loaded Garlic Bread — Standard","Sides","Standard","Sides",1870],
  ["Butcher's Block — Large Original Pan","Pizza","Large","Pizzas",9242],
  ["Butcher's Block — Medium Original Pan","Pizza","Medium","Pizzas",6060],
  ["Cheese Lovers — Large Original Pan","Pizza","Large","Pizzas",9909],
  ["Cheese Lovers — Medium Original Pan","Pizza","Medium","Pizzas",4798],
  ["Cheesy Breadsticks — Standard","Sides","Standard","Sides",3880],
  ["Cheesy Garlic Bread — Standard","Sides","Standard","Sides",2703],
  ["Chicken Supreme — Large Original Pan","Pizza","Large","Pizzas",7468],
  ["Chicken Supreme — Medium Original Pan","Pizza","Medium","Pizzas",4530],
  ["Choc Lava Cake — Standard","Desserts","Standard","Desserts",1422],
  ["Chocolate Mousse — Standard","Desserts","Standard","Desserts",1720],
  ["Chocolate Obsession Ice Cream 500ML — Standard","Desserts","Standard","Desserts",3507],
  ["Coca-Cola® — 1.25l","Drinks","1.25l","ProductGroup",2250],
  ["Coca-Cola® — 375ml","Drinks","375ml","ProductGroup",675],
  ["Coca-Cola® Classic 1.25L — Standard","Drinks","Standard","Drinks",2250],
  ["Coca-Cola® Classic 375ml — Standard","Drinks","Standard","Drinks",675],
  ["Coca-Cola® Vanilla — 1.25l","Drinks","1.25l","ProductGroup",2313],
  ["Coca-Cola® Vanilla — 375ml","Drinks","375ml","ProductGroup",694],
  ["Coca-Cola® Vanilla 1.25L — Standard","Drinks","Standard","Drinks",2313],
  ["Coca-Cola® Vanilla 375ml — Standard","Drinks","Standard","Drinks",694],
  ["Coca-Cola® Zero Sugar — 1.25l","Drinks","1.25l","ProductGroup",18],
  ["Coca-Cola® Zero Sugar — 375ml","Drinks","375ml","ProductGroup",5],
  ["Coca-Cola® Zero Sugar 1.25L — Standard","Drinks","Standard","Drinks",18],
  ["Coca-Cola® Zero Sugar 375ml — Standard","Unreal!","Standard","Drinks",5],
  ["Cookie: Made With NUTELLA — Standard","Desserts","Standard","Desserts",7598],
  ["Creamy Chicken & Bacon — Large Original Pan","Pizza","Large","Pizzas",7628],
  ["Creamy Chicken & Bacon — Medium Original Pan","Pizza","Medium","Pizzas",5366],
  ["Creamy Garlic Dip — Standard","Sides","Standard","Sides",524],
  ["Creamy Garlic Paneer — Large Original Pan","Pizza","Large","Pizzas",5312],
  ["Creamy Garlic Paneer — Medium Original Pan","Pizza","Medium","Pizzas",5312],
  ["Creamy Garlic Prawn (Contains Imported Seafood) — Large Original Pan","Pizza","Large","Pizzas",8424],
  ["Creamy Garlic Prawn (Contains Imported Seafood) — Medium Original Pan","Pizza","Medium","Pizzas",4950],
  ["Diet Coke — 1.25l","Drinks","1.25l","ProductGroup",24],
  ["Diet Coke — 375ml","Drinks","375ml","ProductGroup",11],
  ["Diet Coke 1.25L — Standard","Drinks","Standard","Drinks",24],
  ["Diet Coke 375ML — Standard","Drinks","Standard","Drinks",11],
  ["Fanta® — 1.25l","Drinks","1.25l","ProductGroup",1710],
  ["Fanta® — 375ml","Drinks","375ml","ProductGroup",513],
  ["Fanta® 1.25L — Standard","Drinks","Standard","Drinks",1710],
  ["Fanta® 375ml — Standard","Drinks","Standard","Drinks",513],
  ["Fanta® Lemon — 1.25l","Drinks","1.25l","ProductGroup",1700],
  ["Fanta® Lemon — 375ml","Drinks","375ml","ProductGroup",814],
  ["Fanta® Lemon 1.25L — Standard","Drinks","Standard","Drinks",814],
  ["Fanta® Lemon 375ML — Standard","Drinks","Standard","Drinks",814],
  ["Fanta® Raspberry No Sugar 1.25L — Standard","Drinks","Standard","Drinks",7],
  ["Garlic Bread — Standard","Sides","Standard","Sides",2278],
  ["Ham Lovers — Large Original Pan","Pizza","Large","Pizzas",7256],
  ["Ham Lovers — Medium Original Pan","Pizza","Medium","Pizzas",4402],
  ["Hawaiian — Large Original Pan","Pizza","Large","Pizzas",7391],
  ["Hawaiian — Medium Original Pan","Pizza","Medium","Pizzas",4477],
  ["Hawaiian. — Family Pan Original Pan","Pizza","Family Pan","Pizzas",8731],
  ["Hawaiian. — Large Original Pan","Pizza","Large","Pizzas",7379],
  ["Hawaiian. — Medium Original Pan","Pizza","Medium","Pizzas",6812],
  ["HERSHEY'S Brownie — Standard","Desserts","Standard","Desserts",9270],
  ["HERSHEY'S Cookie — Standard","Desserts","Standard","Desserts",6952],
  ["Hickory & Brown Sugar — 12 Wings","Wings","12 Wings","WingsStreet",5585],
  ["Hickory & Brown Sugar — 6 Wings","Wings","6 Wings","WingsStreet",2792],
  ["Honey Mustard — 12 Wings","Wings","12 Wings","WingsStreet",5410],
  ["Honey Mustard — 6 Wings","Wings","6 Wings","WingsStreet",2705],
  ["Honey Soy — 12 Wings","Wings","12 Wings","WingsStreet",5366],
  ["Honey Soy — 6 Wings","Wings","6 Wings","WingsStreet",2683],
  ["Hot & Spicy Chicken — Large Original Pan","Pizza","Large","Pizzas",7676],
  ["Hot & Spicy Chicken — Medium Original Pan","Pizza","Medium","Pizzas",4745],
  ["Hot & Spicy Veggie — Large Original Pan","Pizza","Large","Pizzas",7218],
  ["Hot & Spicy Veggie — Medium Original Pan","Pizza","Medium","Pizzas",4425],
  ["Hot Chips Large — Standard","Sides","Standard","Sides",2114],
  ["Hot Chips Regular — Standard","Sides","Standard","Sides",1617],
  ["Jalapenos Cheese Bites — 10 cheese bites","Sides","10 cheese bites","ProductGroup",1590],
  ["Jalapenos Cheese Bites — 20 cheese bites","Sides","20 cheese bites","ProductGroup",5300],
  ["Jalapenos Cheese Bites — 6 cheese bites","Sides","6 cheese bites","ProductGroup",2650],
  ["Kirks® Pasito 1.25L — Standard","Drinks","Standard","Drinks",2170],
  ["Korean BBQ — 12 Wings","Wings","12 Wings","WingsStreet",5447],
  ["Korean BBQ — 6 Wings","Wings","6 Wings","WingsStreet",2724],
  ["Margherita — Large Original Pan","Pizza","Large","Pizzas",6793],
  ["Margherita — Medium Original Pan","Pizza","Medium","Pizzas",4145],
  ["Monster Energy 500ml — Standard","Unreal!","Standard","Drinks",986],
  ["Monster Ultra Gold 500ml — Standard","Drinks","Standard","Drinks",45],
  ["Monster Zero Ultra 500ml — Standard","Drinks","Standard","Drinks",37],
  ["No Sauce — 12 Wings","Wings","12 Wings","WingsStreet",5575],
  ["No Sauce — 6 Wings","Wings","6 Wings","WingsStreet",2787],
  ["Paneer Hot & Spicy — Large Original Pan","Pizza","Large","Pizzas",7698],
  ["Pepperoni Lovers — Large Original Pan","Pizza","Large","Pizzas",8153],
  ["Pepperoni Lovers — Medium Original Pan","Pizza","Medium","Pizzas",5206],
  ["Pepperoni Lovers Loaded Garlic Bread — Standard","Sides","Standard","Sides",1922],
  ["Ranch Dip — Standard","Sides","Standard","Sides",448],
  ["Rock Salt Caramel Ice Cream 500ML — Standard","Desserts","Standard","Desserts",3829],
  ["Smoky BBQ — 12 Wings","Wings","12 Wings","WingsStreet",5436],
  ["Smoky BBQ — 6 Wings","Wings","6 Wings","WingsStreet",2718],
  ["Sprite® — 1.25l","Drinks","1.25l","ProductGroup",1881],
  ["Sprite® — 375ml","Drinks","375ml","ProductGroup",564],
  ["Sprite® 1.25L — Standard","Drinks","Standard","Drinks",1881],
  ["Sprite® 375ml — Standard","Drinks","Standard","Drinks",564],
  ["Spud Bites — Standard","Sides","Standard","Sides",1790],
  ["Super Supreme — Large Original Pan","Pizza","Large","Pizzas",7990],
  ["Super Supreme — Medium Original Pan","Pizza","Medium","Pizzas",4905],
  ["Surf & Turf (Contains Imported Seafood) — Large Original Pan","Pizza","Large","Pizzas",7388],
  ["Surf & Turf (Contains Imported Seafood) — Medium Original Pan","Pizza","Medium","Pizzas",4827],
  ["Sweet Chilli Dip — Standard","Sides","Standard","Sides",151],
  ["Tomato Sauce Dip — Standard","Sides","Standard","Sides",99],
  ["Triple Dippers with Cheesy Spud bites — Standard","Sides","Standard","Sides",8079],
  ["Triple Dippers With Spud Bites — Standard","Sides","Standard","Sides",7713],
  ["Ultimate Hot & Spicy — Large Original Pan","Pizza","Large","Pizzas",8205],
  ["Ultimate Hot & Spicy — Medium Original Pan","Pizza","Medium","Pizzas",5088],
  ["Vanilla Bean Ice Cream 500ML — Standard","Desserts","Standard","Desserts",3178],
  ["Veggie Sensation — Large Original Pan","Pizza","Large","Pizzas",8423],
  ["Veggie Sensation — Medium Original Pan","Pizza","Medium","Pizzas",5094],
] as const;
