import { useState } from "react";
import { ArrowLeft, Check, ClipboardPaste, Plus, X } from "lucide-react";
import { db, id } from "./data/db";
import { compatibleQuantity, foodUnitLabel, parseRecipeText, suggestFood, type ImportedRecipe } from "./domain/recipeImport";
import type { CalculationMode, Food, FoodCategory, FoodUnit, Recipe } from "./domain/types";

interface ResolvedIngredient { importedId:string; foodId:string; quantity:number }

export function RecipeImport({foods,categories,onClose,onSaved}:{foods:Food[];categories:FoodCategory[];onClose:()=>void;onSaved:(recipe:Recipe)=>void}) {
  const [text,setText]=useState("");
  const [parsed,setParsed]=useState<ImportedRecipe>();
  const [resolved,setResolved]=useState<ResolvedIngredient[]>([]);
  const [categoryId,setCategoryId]=useState(categories.some(category=>category.id==="other")?"other":categories[0]?.id??"other");
  const [error,setError]=useState("");
  const [creatingFor,setCreatingFor]=useState<string>();
  const parse=()=>{try{const result=parseRecipeText(text);setParsed(result);setResolved(result.ingredients.map(ingredient=>{const match=suggestFood(ingredient.name,foods);return {importedId:ingredient.id,foodId:match?.id??"",quantity:match?compatibleQuantity(ingredient.quantity,ingredient.unit,match):ingredient.quantity??1}}));setError("")}catch(ex){setError(ex instanceof Error?ex.message:"Could not parse recipe")}};
  const update=(importedId:string,foodId:string)=>setResolved(current=>current.map(item=>{if(item.importedId!==importedId)return item;const imported=parsed?.ingredients.find(candidate=>candidate.id===importedId);const food=foods.find(candidate=>candidate.id===foodId);return {...item,foodId,quantity:food?compatibleQuantity(imported?.quantity,imported?.unit,food):item.quantity}}));
  const save=async()=>{try{if(!parsed)return;if(!parsed.name.trim())throw new Error("Recipe name is required");if(!Number.isFinite(parsed.yieldServings)||parsed.yieldServings<=0)throw new Error("Yield must be greater than zero");const unresolved=resolved.filter(item=>!item.foodId);if(unresolved.length)throw new Error(`Match all ${unresolved.length} remaining ingredient${unresolved.length===1?"":"s"}`);if(resolved.some(item=>!Number.isFinite(item.quantity)||item.quantity<=0))throw new Error("Ingredient quantities must be greater than zero");const now=new Date().toISOString();const recipe:Recipe={id:id(),name:parsed.name.trim(),categoryId,yieldServings:parsed.yieldServings,ingredients:parsed.ingredients.map((ingredient,sortIndex)=>{const match=resolved.find(item=>item.importedId===ingredient.id)!;return {id:id(),foodId:match.foodId,quantity:match.quantity,sortIndex,group:ingredient.group}}),instructions:parsed.instructions.length?parsed.instructions:undefined,notes:"Imported from pasted text. Review ingredient matches and quantities against your source.",createdAt:now,updatedAt:now};await db.recipes.add(recipe);onSaved(recipe)}catch(ex){setError(ex instanceof Error?ex.message:"Could not save imported recipe")}};

  if(!parsed)return <section className="recipe-import">
    <header><button onClick={onClose} aria-label="Close recipe import"><X/></button><div><strong>Import recipe</strong><small>Paste text—nothing leaves this device.</small></div><span/></header>
    <div className="import-intro"><ClipboardPaste/><h2>Paste a recipe</h2><p>Use headings for Ingredients and Instructions. Include a Serves or Yield line when available.</p></div>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <label className="import-text">Recipe text<textarea value={text} onChange={e=>setText(e.target.value)} rows={16} autoFocus placeholder={"Spaghetti bolognese\nServes: 4\n\nIngredients\nSauce:\n500 g lean beef mince\n400 ml tomato passata\nPasta:\n400 g spaghetti\n\nInstructions\n1. Brown the beef.\n2. Simmer the sauce."}/></label>
    <button className="primary import-continue" onClick={parse} disabled={!text.trim()}>Review import</button>
  </section>;

  const unresolved=resolved.filter(item=>!item.foodId).length;
  return <section className="recipe-import import-review">
    <header><button onClick={()=>{setParsed(undefined);setError("")}} aria-label="Back to pasted text"><ArrowLeft/></button><div><strong>Review import</strong><small>{unresolved?`${unresolved} ingredient${unresolved===1?"":"s"} need matching`:"Ready to save"}</small></div><button onClick={()=>void save()} aria-label="Save imported recipe" disabled={unresolved>0}><Check/></button></header>
    {error&&<p className="form-error" role="alert">{error}</p>}
    <div className="import-recipe-fields"><label>Recipe name<input value={parsed.name} onChange={e=>setParsed({...parsed,name:e.target.value})}/></label><div><label>Category<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>Yield<input type="number" min="0.1" step="0.1" value={parsed.yieldServings} onChange={e=>setParsed({...parsed,yieldServings:Number(e.target.value)})}/><small>servings</small></label></div></div>
    <div className="import-section-title"><strong>Match ingredients</strong><span>{parsed.ingredients.length}</span></div>
    <div className="import-matches">{parsed.ingredients.map(ingredient=>{const match=resolved.find(item=>item.importedId===ingredient.id)!;const food=foods.find(candidate=>candidate.id===match.foodId);return <article key={ingredient.id} className={match.foodId?"":"unresolved"}><div><strong>{ingredient.name}</strong><small>{ingredient.source}{ingredient.group?` · ${ingredient.group}`:""}{ingredient.note?` · ${ingredient.note}`:""}</small>{ingredient.warning&&<p className="import-warning" role="note">{ingredient.warning}</p>}</div><label><span>Saved food</span><select value={match.foodId} onChange={e=>update(ingredient.id,e.target.value)}><option value="">Choose a food…</option>{foods.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label><span>Recipe quantity</span><span className="import-quantity"><input type="number" min="0.01" step="any" inputMode="decimal" value={match.quantity} onChange={e=>setResolved(current=>current.map(item=>item.importedId===ingredient.id?{...item,quantity:Number(e.target.value)}:item))}/><small>{food?foodUnitLabel(food.baseUnit):ingredient.unit??"units"}</small></span></label>{!match.foodId&&<button className="create-import-food" onClick={()=>setCreatingFor(ingredient.id)}><Plus/>Create “{ingredient.name}”</button>}</article>})}</div>
    {!!parsed.instructions.length&&<section className="import-steps"><strong>Preparation</strong><ol>{parsed.instructions.map((step,index)=><li key={`${index}-${step}`}>{step}</li>)}</ol></section>}
    <button className="primary import-save" onClick={()=>void save()} disabled={unresolved>0}>Save imported recipe</button>
    {creatingFor&&<ImportFoodDialog ingredientName={parsed.ingredients.find(item=>item.id===creatingFor)?.name??""} sourceUnit={parsed.ingredients.find(item=>item.id===creatingFor)?.unit} categories={categories} onClose={()=>setCreatingFor(undefined)} onCreated={food=>{const imported=parsed.ingredients.find(item=>item.id===creatingFor);setResolved(current=>current.map(item=>item.importedId===creatingFor?{...item,foodId:food.id,quantity:compatibleQuantity(imported?.quantity,imported?.unit,food)}:item));setCreatingFor(undefined)}}/>}
  </section>;
}

function ImportFoodDialog({ingredientName,sourceUnit,categories,onClose,onCreated}:{ingredientName:string;sourceUnit?:string;categories:FoodCategory[];onClose:()=>void;onCreated:(food:Food)=>void}) {
  const metric=["g","kg","ml","l"].includes(sourceUnit?.toLowerCase()??"");
  const [name,setName]=useState(ingredientName);
  const [mode,setMode]=useState<CalculationMode>(metric?"per100":"perServing");
  const [unit,setUnit]=useState<FoodUnit>(["ml","l"].includes(sourceUnit?.toLowerCase()??"")?"ml":metric?"g":"serving");
  const [categoryId,setCategoryId]=useState(categories.some(category=>category.id==="other")?"other":categories[0]?.id??"other");
  const [calories,setCalories]=useState("");const [protein,setProtein]=useState("");const [carbohydrates,setCarbohydrates]=useState("");const [fat,setFat]=useState("");const [fibre,setFibre]=useState("");const [error,setError]=useState("");
  const save=async()=>{try{const values=[calories,protein,carbohydrates,fat].map(Number);const fibreValue=fibre.trim()?Number(fibre):undefined;if(!name.trim())throw new Error("Food name is required");if(values.some(value=>!Number.isFinite(value)||value<0)||(fibreValue!==undefined&&(!Number.isFinite(fibreValue)||fibreValue<0)))throw new Error("Nutrition values must be valid and non-negative");const now=new Date().toISOString();const food:Food={id:id(),name:name.trim(),categoryId,calculationMode:mode,baseQuantity:mode==="per100"?100:1,baseUnit:unit,servingDescription:mode==="perServing"?`1 ${unit}`:undefined,calories:values[0]!,protein:values[1]!,carbohydrates:values[2]!,fat:values[3]!,fibre:fibreValue,notes:"Created while reviewing a pasted recipe — verify nutrition against your source.",logCount:0,createdAt:now,updatedAt:now};await db.foods.add(food);onCreated(food)}catch(ex){setError(ex instanceof Error?ex.message:"Could not create food")}};
  return <div className="dialog-backdrop"><div className="dialog import-food-dialog" role="dialog" aria-modal="true"><h2>Create ingredient food</h2><p>This food will be saved locally and matched to the imported ingredient.</p>{error&&<p className="form-error" role="alert">{error}</p>}<label>Name<input value={name} onChange={e=>setName(e.target.value)} autoFocus/></label><div className="import-food-grid"><label>Nutrition basis<select value={mode} onChange={e=>{const next=e.target.value as CalculationMode;setMode(next);setUnit(next==="per100"?"g":"serving")}}><option value="per100">Per 100 g/mL</option><option value="perServing">Per serving</option></select></label><label>Unit<select value={unit} onChange={e=>setUnit(e.target.value as FoodUnit)}>{mode==="per100"?<><option value="g">grams</option><option value="ml">millilitres</option></>:<><option value="serving">serving</option><option value="item">item</option><option value="slice">slice</option><option value="scoop">scoop</option></>}</select></label></div><label>Category<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><div className="import-food-grid nutrients"><label>Calories<input type="number" min="0" inputMode="decimal" value={calories} onChange={e=>setCalories(e.target.value)}/></label><label>Protein (g)<input type="number" min="0" inputMode="decimal" value={protein} onChange={e=>setProtein(e.target.value)}/></label><label>Carbs (g)<input type="number" min="0" inputMode="decimal" value={carbohydrates} onChange={e=>setCarbohydrates(e.target.value)}/></label><label>Fat (g)<input type="number" min="0" inputMode="decimal" value={fat} onChange={e=>setFat(e.target.value)}/></label><label>Fibre (g, optional)<input type="number" min="0" inputMode="decimal" value={fibre} onChange={e=>setFibre(e.target.value)}/></label></div><div><button onClick={onClose}>Cancel</button><button className="primary" onClick={()=>void save()}>Create & match</button></div></div></div>;
}
